language: ruby
rvm:
- 2.1.2
notifications:
  email:
    recipients:
    - clay@smockle.com
    on_success: change
    on_failure: always
before_script:
  - openssl aes-256-cbc -k "$secret" -in config/application.yml.enc -d -a -out config/application.yml
env:
  global:
    secure: INqm1jBkkku9Zm0J/GlB4XIGI4R2KhaszX83EF4k8WaZUOy3GcYZSUNW4QehuTMGdZMR5hlW2PfbgRQgaSLYG8waR73bNbTbnDWWirG6bM+mADX//1nfg8HkzXdC9FzH5HAMOoJqm4TQUw8yW4k5UQi/4esLOwLTpVEVTwAX+8M=
