language: ruby
rvm:
- 2.1.2
notifications:
  email:
    recipients:
    - clay@smockle.com
    on_success: change
    on_failure: always
env:
  global:
    secure: D6HtnnJJPBugywpXk3mGVFPoTJIW6r8FQK0QLgNUv6t0itISUAXrfPXRCAxx8Ffn36kyZ39MUupvHYC9gxvtG/ezeIJqthuv2JEX5OWtGQzpGF2eG8cM+7n4LyeQtrZNn+uMdRyK7+c2z6HprtePhZylPUOlBmiTfCMW1KM5bC8=
