development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: smockle_development
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: smockle_test
  timeout: 5000
