# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Project.create(:name => "Smockle", :client => "Smockle, LLC.", :quote => "Wow.", :description => "I designed and developed a portfolio website for a really fun web design collective. The site is built using the Ruby on Rails framework and is hosted on Heroku. It has been lovingly reworked since fall 2012. Hopefully it impresses you--maybe enough to hire me. I build the Internet. I want to build it with you.", :link => "http://www.smockle.com/")
Project.create(:name => "Employee Directory", :client => "Auburn University - Office of Information Technology", :quote => "The site is so much easier to use now!", :description => "I built an accessible, responsive website for the Office of Information Technology using the ASP.NET MVC framework. The site was developed in two months and has been live since summer 2012. The site is used daily by employees of Auburn University. Employee information is presented in an attractive card layout that flows perfectly on both mobile devices and wall displays. Now it's easy to get connected.", :link => "https://cws.auburn.edu/oit/phone")
Project.create(:name => "News Release", :client => "Auburn University - Office of Information Technology", :quote => "Other departments will want to use this!", :description => "I built an accessible, responisve web application to facilitate mass communication between the Office of Information Technology and the University at large. The site was developed in one month and has been live since spring 2012. Now students and faculty stay informed about everything from planned site maintenance to free t-shirts.", :link => "https://cws.auburn.edu/oit/news")
Project.create(:name => "Classroom Administration", :client => "Auburn University - Office of Information Technology", :quote => "We are impressed with what we've seen.", :description => "I designed and built a website for the Office of Information Technology using the ASP.NET MVC framework. The site was developed in three days and has been live since spring 2013. Information about the technology in each University classroom is presented in an attractive flipping table.", :link => "https://cws.auburn.edu/oit/tec")
Project.create(:name => "Educational Resources", :client => "Alabama State Department of Education", :quote => "We are very pleased with Clay's work on the website, he's doing great things for us!", :description => "I built an accessible, responsive website for the Alabama Science in Motion program using the ASP.NET MVC framework. The site was developed in eight months. Today the site connects hundreds of students and educators across the state. Now it's easy to view lab materials and photos, learn about education standards, and contact a regional science specialist.", :link => "https://cws.auburn.edu/asim")
Project.create(:name => "Faculty Profiles", :client => "Auburn University - Office of Institutional Research", :quote => "Thanks for your great work, Clay.", :description => "I designed and built a website for the Office of Institutional Research using the ASP.NET MVC framework. The site was developed in four months. Every grant, publication and presentation from every professor in the University is searchable and viewable from one attractive site.", :link => "https://cws.auburn.edu/fai")
Project.create(:name => "Photo Gallery", :client => "Auburn United Methodist Church", :quote => "You could sell this.", :description => "I designed and developed a website to aggregate photos Instagrammed during an event. The site is built using the Ruby on Rails framework and is hosted on Heroku. The site was developed in five hours and has been live since fall 2013.", :link => "http://couches.herokuapp.com")
Project.create(:name => "Event Promotion", :client => "Auburn University - Office of Information Technology", :quote => "Oh yes, I really love that background.", :description => "This website was developed in collaboration with Javakat. I designed and coded the background collage of rotating Flickr images. <a href=\"javakat.io\">Javakat</a> provided the copy and markup. The site was developed in a week and has been live since fall 2013.", :link => "https://cws.auburn.edu/oit/cws/home/")
Project.create(:name => "Organization Details", :client => "American Civil Liberties Union of Alabama", :quote => "Wow, this is a great start. It is a lot cleaner and more modern looking.", :description => "I styled and built an website using WordPress as a content managment system. The site was developed in two months. Information about the ACLU's mission, stucture and current work is delivered in a readable, modern format. The site offers multiple opportunities to connect, via contact forms, donation links and Twitter integration.", :link => "http://aclualabama.org/wp")
Project.create(:name => "Test Scheduling", :client => "Auburn University - Biggio Center for the Enhancement of Teaching or Learning", :quote => "That site is really pretty.", :description => "I designed and began developing a website using the ASP.NET MVC framework and AngularJS. I worked on the site for three months. Events can be viewed and scheduled on a calendar built using CSS Flexible Boxes.", :link => "http://cwsmigr.auburn.edu/big")
Project.create(:name => "Career Resources", :client => "Auburn University - Career Center", :quote => "I love this site. You're earning your paycheck!", :description => "I designed and built an accessible, responsive website using the Laravel MVC framework. Each content section updates dynamically as content is tweeted, scheduled, or blogged. The site was developed in three weeks and will go live in spring 2014.", :link => "http://auburn.edu/career/laravel")
Project.create(:name => "Icon Design", :client => "Pierce Boggan & Auburn Mobile", :quote => "Those are excellent!", :description => "I created tab bar icons for two iOS apps using Adobe Illustrator. I worked hard to find expressive metaphors for abstract concepts like \"memorization\". The design process took about ten hours. Both apps will be available from the App Store in spring 2014.", :link => "http://www.smockle.com")