# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
# Projects:
#
#   How did you get the job?
#   Who did you work with?
#   What will the site do?
#   What language and tools did you use?
#   Did you use anything new during development?
#   Were there any surprises during development or testing?
#   How long did development take?
#   Has the site launched?
#   Who uses the site now?
Reason.create(:reason => "I have a project I'd like to talk about.", :reason_es => "Me gustar\u00EDa hablar sobre un proyecto.")
Reason.create(:reason => "I want to hear more about your abilities.", :reason_es => "Quiero aprender m\u00E1s acerca de sus habilidades.")
Reason.create(:reason => "Nope. Something else.", :reason_es => "Algo m\u00E1s.")
Project.create(:client => "Alabama Science in Motion", :name => "Educational Website", :name_es => "Sitio educativo", :quote => "\"We came to the right place.\"", :quote_es => "\"Llegamos al lugar correcto.\"", :message => "<p>I met with folks from the Alabama Science in Motion program several times to plan and review an entirely <a href=\"http://cws.auburn.edu/asim\">new website</a> that I built in HTML/C# with the ASP.NET MVC Framework.</p><p>The existing Science in Motion website had become difficult to maintain. With good reason--the site is large and complex. It connects hundreds of students and educators across the state with science resources provided by twelve Alabama universities. The site's content includes contact information, maps, lists of links, and downloadable lab materials.</p><p>I designed the new site to do all of that, while making it faster, more flexible, and more accessible. The new site allows labs and standards to be searched and filtered. Site admins also have finer control over site presentation and permissions. The new site is expected to go live in early 2013, following eight months of development.</p>", :message_es => "<p>Me encontr\u00E9 con la gente de Alabama Science in Motion varias veces para planificar y revisar un <a href=\"http://cws.auburn.edu/asim\">nuevo sitio web</a> que constru\u00ED con HTML y C# con ASP.NET MVC.</p><p>El sitio existente se ha vuelto dif\u00EDcil para mantener. El sitio nuevo es m\u00E1s r\u00E1pido, m\u00E1s adaptable y m\u00E1s accesible. Despu\u00E9s de la implementaci\u00F3n final, el sitio ser\u00E1 utilizado por cientos de estudiantes y educadores en todo Alabama.</p>")
Project.create(:client => "Auburn University", :name => "Employee Directory", :name_es => "Directorio de empleados", :quote => "\"The site is so much easier to use now!\"", :quote_es => "\"\u00A1El sitio es mucho m\u00E1s f\u00E1cil de usar ahora!\"", :message => "<p>For several years, the Office of Information Technology relied on an employee phone directory that was full of incorrect information and could not be searched. I rewrote the site using HTML/C# with the ASP.NET MVC framework, redesigning the layouts and adding useful features.</p><p>The new website ties into the main Auburn University database. This means that employees are added and removed from the list automatically, and their data is always up to date. Employees can also modify their own data, should any problems arise. The information is presented in an attractive card layout by default, and can be searched or filtered based on a number of parameters. As requested, there is also a list and report view.</p><p>The rewrite took approximately two months, and the site has been live since summer 2012. The finished website is used daily by employees of Auburn University, and powers a number of kiosks throughout the Office of Information technology building. The site's responsive design makes it easy to use on mobile devices, so the process of looking up and calling a coworker is faster than ever.</p>", :message_es => "\u00A1Pr\u00F3ximamente!")
Project.create(:client => "Auburn University", :name => "News Distribution Platform", :name_es => "Plataforma de distribuci\u00F3n de noticias", :quote => "\"Other departments will want to use this!\"", :quote_es => "\"\u00A1Otros departamentos tendr\u00E1n que usar esta!\"", :message => "<p>The Auburn University Webmaster asked me to develop a web application which would allow approved employees to post University and technology-related news. The finished product was admired for its simplicity: users typed their news once and submitted to multiple sources using a single form. At launch, the application supported Facebook and Twitter via their respective APIs. After additional development, I added support for the Office of Information Technology blog and several University mailing lists.</p><p>The application has been in use since spring 2012, following one month of development. It has facilitated mass communication between the Office of Information Technology and the University at large. Students and faculty have become more informed about a number of topics, from planned site maintenance to free t-shirts.</p>", :message_es => "\u00A1Pr\u00F3ximamente!")
Project.create(:client => "Smockle, LLC.", :name => "Portfolio Website", :name_es => "Cartera de web", :quote => "\"Wow.\"", :quote_es => "\"Wow.\"", :message => "<p>Smockle is an Internet company. Because I write websites for a living, I wanted my own site to reflect everything I've learned and experienced on the web. I wanted to integrate with innovative web services like <a href=\"http://flattr.com/thing/1075860/Smockle\">Flattr</a> and <a href=\"https://twitter.com/SmockleWeb\">Twitter</a>, and I wanted to show off cutting-edge web design techniques. I wanted to impress you so that maybe you'll <a href=\"contact\">hire me</a>.</p><p>I built this site using the powerful and flexible Ruby on Rails framework. Twitter Bootstrap provides a solid base for a custom responsive design. I use AppFog to host the site, and I use Google Webmaster Tools to help manage it.</p><p>I spent about a month planning and developing this site, and during that month I worked tirelessly to deliver the best possible web experience. Because that's what I do; I build the Internet. And I can do it again. <a href=\"contact\">For you</a>.</p>", :message_es => "\u00A1Pr\u00F3ximamente!")