# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Project.create(:name => "Faculty Profiles", :client => "Auburn University - Office of Institutional Research", :quote => "Thanks for your great work, Clay.", :description => "I designed and built a website for the Office of Institutional Research using the ASP.NET MVC framework. The site was developed in four months. Every grant, publication and presentation from every professor in the University is searchable and viewable from one attractive site.", :offset_x => 50, :offset_y => 50, :link => "https://cws.auburn.edu/fai")
Project.create(:name => "Educational Resources", :client => "Alabama State Department of Education", :quote => "We are very pleased with Clay's work on the website, he's doing great things for us!", :description => "I built an accessible, responsive website for the Alabama Science in Motion program using the ASP.NET MVC framework. The site was developed in eight months. Today the site connects hundreds of students and educators across the state. Now it's easy to view lab materials and photos, learn about education standards, and contact a regional science specialist.", :offset_x => 40, :offset_y => 42, :link => "https://cws.auburn.edu/asim")
Project.create(:name => "Classroom Administration", :client => "Auburn University - Office of Information Technology", :quote => "We are impressed with what we've seen.", :description => "I designed and built a website for the Office of Information Technology using the ASP.NET MVC Framework. The site was developed in three days and has been live since spring 2013. Information about the technology in each University classroom is presented in an attractive flipping table.", :offset_x => 50, :offset_y => 64, :link => "https://cws.auburn.edu/oit/tec")
Project.create(:name => "News Release", :client => "Auburn University - Office of Information Technology", :quote => "Other departments will want to use this!", :description => "I built an accessible, responisve web application to facilitate mass communication between the Office of Information Technology and the University at large. The site was developed in one month and has been live since spring 2012. Now students and faculty stay informed about everything from planned site maintenance to free t-shirts.", :offset_x => 47, :offset_y => 23, :link => "https://cws.auburn.edu/oit/news")
Project.create(:name => "Employee Directory", :client => "Auburn University - Office of Information Technology", :quote => "The site is so much easier to use now!", :description => "I built an accessible, responsive website for the Office of Information Technology using the ASP.NET MVC framework. The site was developed in two months and has been live since summer 2012. The site is used daily by employees of Auburn University. Employee information is presented in an attractive card layout that flows perfectly on both mobile devices and wall displays. Now it's easy to get connected.", :offset_x => 16, :offset_y => 54, :link => "https://cws.auburn.edu/oit/phone")
Project.create(:name => "Smockle", :client => "Smockle, LLC.", :quote => "Wow.", :description => "I designed and developed a portfolio website for a really fun web design collective. The site is built using the Ruby on Rails framework and is hosted on Heroku. It has been lovingly reworked since fall 2012. Hopefully it impresses you--maybe enough to hire me. I build the Internet. I want to build it with you.", :offset_x => 50, :offset_y => 100, :link => "http://www.smockle.com/")